[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fraud_detection_ml"
version = "0.0.1"
description = "Fraud Detection Project encompassing Deep Learning, QML, and Traditional ML Algorithms"
authors = [
  { name = "Cheng Wei Lun" },
]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "cycler>=0.12.1",
    "graphviz>=0.21",
    "imblearn>=0.0",
    "ipywidgets>=8.1.7",
    "lightgbm[gpu]>=4.6.0",
    "lightning>=2.5.5",
    "loguru",
    "matplotlib>=3.10.7",
    "mkdocs",
    "mlflow>=3.5.0",
    "numpy==1.26.4",
    "optuna>=4.5.0",
    "pandas==2.0.3",
    "pip",
    "plotly>=6.3.1",
    "pyspark>=4.0.1",
    "python-crfsuite>=0.9.11",
    "python-dotenv",
    "ray>=2.49.2",
    "ruff",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "setuptools>=80.9.0",
    "shap>=0.49.1",
    "skorch>=1.2.0",
    "spark>=0.2.1",
    "sweetviz>=2.3.1",
    "torch>=2.9.0",
    "torchsummary>=1.5.1",
    "torchview>=0.2.7",
    "torchvision>=0.24.0",
    "tqdm",
    "typer",
    "wandb>=0.22.2",
    "xgboost>=3.1.1",
    "yellowbrick>=1.5",
]
requires-python = ">=3.12.0"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.ruff]
line-length = 88
src = ["src"]
include = ["pyproject.toml", "src/**/*.py", "notebooks/*.ipynb"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["fraud_detection_ml"]
force-sort-within-sections = true

