_wandb:
    value:
        cli_version: 0.22.2
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 5
                - 8
                - 53
            "2":
                - 5
                - 8
                - 53
            "3":
                - 2
                - 14
            "4": 3.12.11
            "5": 0.22.2
            "8":
                - 1
            "12": 0.22.2
            "13": darwin-arm64
bagging_fraction:
    value: 0.6090015441939779
bagging_freq:
    value: 4
boosting_type:
    value: gbdt
feature_fraction:
    value: 0.7161183995720385
lambda_l1:
    value: 4.19054048435536
lambda_l2:
    value: 4.43822749155359
learning_rate:
    value: 0.037862459283177295
max_bin:
    value: 499
max_depth:
    value: 11
min_data_in_leaf:
    value: 73
min_gain_to_split:
    value: 0.4800222617062655
num_iterations:
    value: 563
num_leaves:
    value: 269
path_smooth:
    value: 84.76736885507388
