_wandb:
    value:
        cli_version: 0.22.2
        e:
            9b018olupywbjykw11c8cg50oalv8g3e:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                    swapTotalBytes: "5368709120"
                codePath: notebooks/03-cwl-lightgbm.ipynb
                codePathLocal: notebooks/03-cwl-lightgbm.ipynb
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "419082706944"
                email: wlunlun1212@gmail.com
                executable: /Users/lunlun/Downloads/Github/Fraud-Detection-ML/.venv/bin/python
                git:
                    commit: 1f88f667ff42bef16494e1bcecc7329ba3755250
                    remote: https://github.com/luuuneytunes12/Fraud-Detection-ML
                host: Chengs-MacBook-Pro.local
                memory:
                    total: "19327352832"
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/lunlun/Downloads/Github/Fraud-Detection-ML/notebooks/03-cwl-lightgbm.ipynb
                python: CPython 3.12.11
                root: /Users/lunlun/Downloads/Github/Fraud-Detection-ML
                startedAt: "2025-10-26T12:46:34.328194Z"
                writerId: 9b018olupywbjykw11c8cg50oalv8g3e
        m:
            - "1": train_binary_logloss
              "6":
                - 3
              "7":
                - 1
            - "1": train_auc
              "6":
                - 3
              "7":
                - 2
            - "1": train_average_precision
              "6":
                - 3
              "7":
                - 2
            - "1": val_binary_logloss
              "6":
                - 3
              "7":
                - 1
            - "1": val_auc
              "6":
                - 3
              "7":
                - 2
            - "1": val_average_precision
              "6":
                - 3
              "7":
                - 2
        python_version: 3.12.11
        t:
            "1":
                - 5
                - 8
                - 53
            "2":
                - 5
                - 8
                - 53
            "3":
                - 2
                - 7
                - 13
                - 15
                - 16
                - 25
                - 63
            "4": 3.12.11
            "5": 0.22.2
            "8":
                - 1
            "10":
                - 20
            "12": 0.22.2
            "13": darwin-arm64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            pr:
                panel_config:
                    fieldSettings:
                        class: class
                        x: recall
                        "y": precision
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: Precision-Recall Curve
                        x-axis-title: Recall
                        y-axis-title: Precision
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: pr_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            roc:
                panel_config:
                    fieldSettings:
                        class: class
                        x: fpr
                        "y": tpr
                    panelDefId: wandb/area-under-curve/v0
                    stringSettings:
                        title: ROC Curve
                        x-axis-title: False positive rate
                        y-axis-title: True positive rate
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: roc_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
boosting_type:
    value: gbdt
class_weight:
    value: null
colsample_bytree:
    value: 1
device_type:
    value: cpu
fold:
    value: 0
force_col_wise:
    value: true
importance_type:
    value: split
learning_rate:
    value: 0.1
max_depth:
    value: 5
metric:
    value:
        - binary_logloss
        - auc
        - average_precision
        - binary
min_child_samples:
    value: 20
min_child_weight:
    value: 0.001
min_split_gain:
    value: 0
n_estimators:
    value: 100
n_folds:
    value: 5
n_jobs:
    value: -1
num_iterations:
    value: 100
num_leaves:
    value: 31
num_threads:
    value: 11
objective:
    value: binary
pipeline:
    value: SMOTE + LGBMClassifier
random_state:
    value: 42
reg_alpha:
    value: 0
reg_lambda:
    value: 0
subsample:
    value: 1
subsample_for_bin:
    value: 200000
subsample_freq:
    value: 0
verbose:
    value: -1
