_wandb:
    value:
        cli_version: 0.22.2
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 5
                - 8
                - 53
            "2":
                - 5
                - 8
                - 53
            "3":
                - 2
                - 14
            "4": 3.12.11
            "5": 0.22.2
            "8":
                - 1
            "12": 0.22.2
            "13": darwin-arm64
bagging_fraction:
    value: 0.6546740162731232
bagging_freq:
    value: 1
boosting_type:
    value: gbdt
feature_fraction:
    value: 0.8361743332357356
lambda_l1:
    value: 8.235527973379398
lambda_l2:
    value: 9.78836593673774
learning_rate:
    value: 0.21591044245139035
max_bin:
    value: 169
max_depth:
    value: 4
min_data_in_leaf:
    value: 24
min_gain_to_split:
    value: 0.025770718954289396
num_iterations:
    value: 834
num_leaves:
    value: 193
path_smooth:
    value: 87.89423565487893
