_wandb:
    value:
        cli_version: 0.22.2
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 5
                - 8
                - 53
            "2":
                - 5
                - 8
                - 53
            "3":
                - 2
                - 14
            "4": 3.12.11
            "5": 0.22.2
            "8":
                - 1
            "12": 0.22.2
            "13": darwin-arm64
bagging_fraction:
    value: 0.8709972568318513
bagging_freq:
    value: 1
boosting_type:
    value: gbdt
feature_fraction:
    value: 0.6641028155675535
lambda_l1:
    value: 5.071165868375306
lambda_l2:
    value: 9.505283376502264
learning_rate:
    value: 0.007515748748218427
max_bin:
    value: 211
max_depth:
    value: 5
min_data_in_leaf:
    value: 13
min_gain_to_split:
    value: 4.5384282916648315
num_iterations:
    value: 705
num_leaves:
    value: 70
path_smooth:
    value: 92.48538882564768
