_wandb:
    value:
        cli_version: 0.22.2
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 5
                - 8
                - 53
            "2":
                - 5
                - 8
                - 53
            "3":
                - 2
                - 14
            "4": 3.12.11
            "5": 0.22.2
            "8":
                - 1
            "12": 0.22.2
            "13": darwin-arm64
bagging_fraction:
    value: 0.5078575841695266
bagging_freq:
    value: 1
boosting_type:
    value: dart
feature_fraction:
    value: 0.8342125044605868
lambda_l1:
    value: 0.43455024970936895
lambda_l2:
    value: 8.482205541860786
learning_rate:
    value: 0.011891853810609304
max_bin:
    value: 98
max_depth:
    value: 10
min_data_in_leaf:
    value: 76
min_gain_to_split:
    value: 2.3541653506411913
num_iterations:
    value: 830
num_leaves:
    value: 213
path_smooth:
    value: 50.932739086463194
