_wandb:
    value:
        cli_version: 0.22.2
        e:
            6ue855k5e7k2i5ojc5qih30ozsp707sd:
                apple:
                    ecpuCores: 6
                    gpuCores: 14
                    memoryGb: 18
                    name: Apple M3 Pro
                    pcpuCores: 5
                    ramTotalBytes: "19327352832"
                    swapTotalBytes: "5368709120"
                codePath: notebooks/03-cwl-lightgbm.ipynb
                codePathLocal: notebooks/03-cwl-lightgbm.ipynb
                cpu_count: 11
                cpu_count_logical: 11
                disk:
                    /:
                        total: "494384795648"
                        used: "418870263808"
                email: wlunlun1212@gmail.com
                executable: /Users/lunlun/Downloads/Github/Fraud-Detection-ML/.venv/bin/python
                git:
                    commit: 1f88f667ff42bef16494e1bcecc7329ba3755250
                    remote: https://github.com/luuuneytunes12/Fraud-Detection-ML
                host: Chengs-MacBook-Pro.local
                memory:
                    total: "19327352832"
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/lunlun/Downloads/Github/Fraud-Detection-ML/notebooks/03-cwl-lightgbm.ipynb
                python: CPython 3.12.11
                root: /Users/lunlun/Downloads/Github/Fraud-Detection-ML
                startedAt: "2025-10-26T11:37:53.814701Z"
                writerId: 6ue855k5e7k2i5ojc5qih30ozsp707sd
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 5
                - 8
                - 53
            "2":
                - 5
                - 8
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.12.11
            "5": 0.22.2
            "8":
                - 1
            "12": 0.22.2
            "13": darwin-arm64
boosting_type:
    value: gbdt
class_weight:
    value: null
colsample_bytree:
    value: 1
device_type:
    value: cpu
force_col_wise:
    value: true
importance_type:
    value: split
learning_rate:
    value: 0.1
max_depth:
    value: 5
min_child_samples:
    value: 20
min_child_weight:
    value: 0.001
min_split_gain:
    value: 0
n_estimators:
    value: 100
n_folds:
    value: 5
n_jobs:
    value: -1
num_leaves:
    value: 31
objective:
    value: binary
pipeline:
    value: SMOTE + LGBMClassifier
random_state:
    value: 42
reg_alpha:
    value: 0
reg_lambda:
    value: 0
subsample:
    value: 1
subsample_for_bin:
    value: 200000
subsample_freq:
    value: 0
verbose:
    value: -1
